import {afterEach,describe,it,expect,vi} from 'vitest';
import {ProcessModeler,type ProcessProjection,type ProcessSelectionItem} from '../../src/patterns/process-modeler/index.js';
const graph:ProcessProjection={boxes:[{id:'start',kind:'start',title:'Start',node:{}},{id:'a',kind:'call',title:'A',node:{}},{id:'frame',kind:'try',title:'Frame',frame:true,node:{}},{id:'child',kind:'call',title:'Child',parentId:'frame',node:{}},{id:'section',kind:'section',title:'Section',frame:true,node:{}}],lines:[{id:'sa',from:'start',to:'a'},{id:'ac',from:'a',to:'child'}]};
function fixture(){const b=new ProcessModeler();b.document=structuredClone(graph);document.body.append(b);b.layout={boxes:b.layout.boxes,notes:[{id:'a',text:'Note',x:100,y:200}]};const r=b.shadowRoot!,canvas=r.querySelector<HTMLElement>('[part=canvas]')!;const key=(key:string,extra={})=>{const e=new KeyboardEvent('keydown',{key,bubbles:true,cancelable:true,...extra});canvas.dispatchEvent(e);return e;};return{b,r,canvas,key};}
afterEach(()=>document.body.replaceChildren());
describe('mixed graph selection',()=>{
 it('Ctrl+A selects graph boxes, notes and every line, excludes sections, preserves focus/history',()=>{const{b,r,canvas,key}=fixture();canvas.focus();key('a',{ctrlKey:true});expect(b.selection).toEqual([{type:'box',id:'start'},{type:'box',id:'a'},{type:'box',id:'frame'},{type:'box',id:'child'},{type:'line',id:'sa'},{type:'line',id:'ac'},{type:'note',id:'a'}]);expect(r.activeElement).toBe(canvas);expect(r.querySelector('[data-note-id=a]')!.getAttribute('aria-pressed')).toBe('true');expect(r.querySelector('[data-line-id=sa][part=line]')!.getAttribute('data-selected')).toBe('true');expect(key('z',{ctrlKey:true}).defaultPrevented).toBe(false);});
 it('filters stale IDs, namespaces collisions, deduplicates and detaches caller/returned selections',()=>{const{b}=fixture();const items:ProcessSelectionItem[]=[{type:'box',id:'a'},{type:'note',id:'a'},{type:'line',id:'sa'},{type:'box',id:'missing'},{type:'note',id:'a'}];b.selectItems(items);(items[0] as any).id='start';(b.selection[0] as any).id='child';expect(b.selection).toEqual([{type:'box',id:'a'},{type:'line',id:'sa'},{type:'note',id:'a'}]);b.select('a');expect(b.selection).toEqual([{type:'box',id:'a'}]);b.selectLine('sa');expect(b.selection).toEqual([{type:'line',id:'sa'}]);b.selectMany(['a']);expect(b.selection).toEqual([{type:'box',id:'a'}]);});
 it('emits one atomic mixed delete and leaves unsupported hosts unchanged',()=>{const{b,key}=fixture();const edits=vi.fn();b.addEventListener('process-edit-request',edits);key('a',{ctrlKey:true});const before=b.document,layout=b.layout;key('Delete');expect(edits).toHaveBeenCalledOnce();const request=edits.mock.calls[0][0].detail;expect(request.type).toBe('delete-selection');expect(request.selection).toEqual(b.selection);expect(Object.isFrozen(request.selection)).toBe(true);expect(Object.isFrozen(request.selection[0])).toBe(true);expect(b.document).toBe(before);expect(b.layout).toEqual(layout);});
 it('records accepted mixed selection with atomic undo/redo and ignores repeated acceptance',()=>{const{b,key}=fixture();key('a',{ctrlKey:true});const before=b.selection,beforeLayout=b.layout;const after:ProcessProjection={boxes:[graph.boxes[0]],lines:[]};b.addEventListener('process-edit-request',event=>{const q=(event as CustomEvent).detail;b.document=after;q.accept({layout:{boxes:{start:beforeLayout.boxes.start},notes:[]},selection:[{type:'box',id:'start'}],undo:()=>{b.document=graph;},redo:()=>{b.document=after;}});q.accept({undo:()=>{throw Error('repeated');},redo(){}});});key('Delete');expect(b.selection).toEqual([{type:'box',id:'start'}]);b.undo();expect(b.selection).toEqual(before);expect(b.layout).toEqual(beforeLayout);b.redo();expect(b.selection).toEqual([{type:'box',id:'start'}]);});
 it('uses a distinct mixed-copy contract so legacy hosts cannot silently drop notes/edges',()=>{const{b,key}=fixture();const legacy=vi.fn(),mixed=vi.fn();b.addEventListener('process-copy-request',legacy);key('a',{ctrlKey:true});expect(key('c',{ctrlKey:true}).defaultPrevented).toBe(false);expect(legacy).not.toHaveBeenCalled();b.addEventListener('process-selection-copy-request',event=>{const q=(event as CustomEvent).detail;mixed(q.selection);q.capture({itemCount:5,paste:vi.fn()});});expect(key('c',{metaKey:true}).defaultPrevented).toBe(true);expect(mixed).toHaveBeenCalledWith(b.selection);b.selectItems([{type:'line',id:'sa'}]);key('c',{ctrlKey:true});expect(mixed).toHaveBeenCalledOnce();});
 it('nudges selected notes and roots/descendants once in one reversible layout edit',()=>{const{b,key}=fixture();b.selectItems([{type:'box',id:'frame'},{type:'box',id:'child'},{type:'note',id:'a'},{type:'line',id:'sa'}]);const before=b.layout;key('ArrowRight');expect(b.layout.boxes.frame.x).toBe(before.boxes.frame.x+16);expect(b.layout.boxes.child.x).toBe(before.boxes.child.x+16);expect(b.layout.boxes.a).toEqual(before.boxes.a);expect(b.layout.notes![0].x).toBe(116);b.undo();expect(b.layout).toEqual(before);b.redo();expect(b.layout.notes![0].x).toBe(116);});



 it('records mixed deletion before a queued observer move and preserves undo chronology',()=>{const{b}=fixture();b.selectItems([{type:'line',id:'sa'},{type:'note',id:'a'}]);const before=b.layout,original=b.document!;b.addEventListener('selection-changed',()=>b.move('a',160,b.layout.boxes.a.y),{once:true});b.addEventListener('process-edit-request',event=>{const q=(event as CustomEvent).detail;const after={boxes:graph.boxes,lines:[graph.lines[1]]};b.document=after;q.accept({layout:{boxes:before.boxes,notes:[]},selection:[],undo:()=>{b.document=original;},redo:()=>{b.document=after;}});});b.requestEdit({type:'delete-selection',selection:b.selection});expect(b.layout.boxes.a.x).toBe(160);expect(b.document!.lines).toHaveLength(1);b.undo();expect(b.layout.boxes.a.x).toBe(before.boxes.a.x);expect(b.document!.lines).toHaveLength(1);b.undo();expect(b.document).toBe(original);expect(b.layout).toEqual(before);});
 it('expires queued mixed-deletion notifications when an observer replaces the load session',()=>{const{b}=fixture();b.selectItems([{type:'line',id:'sa'},{type:'note',id:'a'}]);const before=b.layout,original=b.document!;const replacement:ProcessProjection={boxes:[{id:'replacement',kind:'call',title:'Replacement',node:{}}],lines:[]};const positions=vi.fn();b.addEventListener('positions-changed',positions);b.addEventListener('selection-changed',()=>b.load(replacement),{once:true});b.addEventListener('process-edit-request',event=>{const q=(event as CustomEvent).detail;b.document={boxes:graph.boxes,lines:[graph.lines[1]]};q.accept({layout:{boxes:before.boxes,notes:[]},selection:[],undo:()=>{b.document=original;},redo(){}});});b.requestEdit({type:'delete-selection',selection:b.selection});expect(b.document).toBe(replacement);expect(b.selection).toEqual([]);expect(positions).not.toHaveBeenCalled();b.undo();expect(b.document).toBe(replacement);});
 it('retains real note focus through repeated nudge and keyboard undo',()=>{const{b,r}=fixture();let note=r.querySelector<HTMLElement>('[data-note-id=a]')!;note.focus();note.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true}));note.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true,cancelable:true}));expect((r.activeElement as HTMLElement)?.dataset.noteId).toBe('a');r.activeElement!.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true,cancelable:true}));expect(b.layout.notes![0].x).toBe(132);r.activeElement!.dispatchEvent(new KeyboardEvent('keydown',{key:'z',ctrlKey:true,bubbles:true,cancelable:true}));expect(b.layout.notes![0].x).toBe(116);expect((r.activeElement as HTMLElement)?.dataset.noteId).toBe('a');});
 it.each(['graph','note'])('honors host move-request cancellation for %s keyboard nudges',mode=>{const{b,key}=fixture();if(mode==='graph')key('a',{ctrlKey:true});else b.selectItems([{type:'note',id:'a'}]);const before=b.layout,move=vi.fn((event:Event)=>event.preventDefault());b.addEventListener(mode==='note'?'note-move-request':'move-request',move);key('ArrowRight');expect(move).toHaveBeenCalledOnce();expect(b.layout).toEqual(before);expect(key('z',{ctrlKey:true}).defaultPrevented).toBe(false);});
 it('reanchors note-only and multi-line toolbars through selection, pan and zoom',()=>{const{b,r,canvas}=fixture();Object.defineProperties(canvas,{clientWidth:{value:1000},clientHeight:{value:800}});b.setView({x:0,y:0,zoom:1});b.select('a');const toolbar=r.querySelector<HTMLElement>('[part=selection-toolbar]')!;b.selectItems([{type:'note',id:'a'}]);expect(toolbar.style.left).toBe('100px');expect(toolbar.style.top).toBe('152px');b.setView({x:20,y:30,zoom:.5});expect(toolbar.style.left).toBe('70px');expect(toolbar.style.top).toBe('82px');b.selectItems([{type:'line',id:'sa'},{type:'line',id:'ac'}]);const old={left:toolbar.style.left,top:toolbar.style.top};b.setView({x:80,y:90,zoom:1});expect({left:toolbar.style.left,top:toolbar.style.top}).not.toEqual(old);});

 it('keeps the legacy move payload guaranteed and isolates note-only movement',()=>{const{b,key}=fixture();const legacy=vi.fn((event:Event)=>{const d=(event as CustomEvent).detail;expect(typeof d.boxId).toBe('string');expect(Number.isFinite(d.position.x)).toBe(true);event.preventDefault();});const notes=vi.fn((event:Event)=>event.preventDefault());b.addEventListener('move-request',legacy);b.addEventListener('note-move-request',notes);b.selectItems([{type:'note',id:'a'}]);const before=b.layout;key('ArrowRight');expect(legacy).not.toHaveBeenCalled();expect(notes).toHaveBeenCalledOnce();expect(b.layout).toEqual(before);key('a',{ctrlKey:true});key('ArrowRight');expect(legacy).toHaveBeenCalledOnce();expect(b.layout).toEqual(before);});
 it('prunes removed lines/notes on controlled echo and clears all kinds on load',()=>{const{b,key}=fixture();key('a',{ctrlKey:true});const events=vi.fn();b.addEventListener('selection-changed',events);b.document={boxes:graph.boxes,lines:[]};expect(b.selection.filter(item=>item.type==='line')).toEqual([]);expect(events.mock.calls.at(-1)![0].detail.selection).toEqual(b.selection);b.layout={boxes:b.layout.boxes,notes:[]};expect(b.selection.filter(item=>item.type==='note')).toEqual([]);b.load(graph);expect(b.selection).toEqual([]);});
 it('reads inherited selection descriptors explicitly and refuses malformed deletion',()=>{const{b}=fixture();const edits=vi.fn();b.addEventListener('process-edit-request',edits);b.requestEdit({type:'delete-selection',selection:[Object.create({get type(){return 'note';},get id(){return 'a';}})]} as any);expect(edits.mock.calls[0][0].detail.selection).toEqual([{type:'note',id:'a'}]);b.requestEdit({type:'delete-selection',selection:[]} as any);b.requestEdit({type:'delete-selection',selection:[{type:'unknown',id:'a'}]} as any);expect(edits).toHaveBeenCalledOnce();});
 it('aligns only boxes without moving selected notes or sections',()=>{const{b}=fixture();b.selectItems([{type:'box',id:'a'},{type:'box',id:'child'},{type:'note',id:'a'}]);const before=b.layout;b.arrangeSelection('top');expect(b.layout.notes).toEqual(before.notes);expect(b.layout.boxes.section).toEqual(before.boxes.section);});
 it('preserves text-field select-all and copy behavior',()=>{const{b,r}=fixture();const input=r.querySelector<HTMLInputElement>('[part=search]')!;const e=new KeyboardEvent('keydown',{key:'a',ctrlKey:true,bubbles:true,cancelable:true});input.dispatchEvent(e);expect(e.defaultPrevented).toBe(false);expect(b.selection).toEqual([]);});
 it('supports note keyboard activation, lock and disabled connection refusal without losing selection',()=>{const{b,r,key}=fixture();const note=r.querySelector<HTMLElement>('[data-note-id=a]')!;note.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true}));expect(b.selection).toEqual([{type:'note',id:'a'}]);key('a',{ctrlKey:true});const edits=vi.fn();b.addEventListener('process-edit-request',edits);b.locked=true;key('Delete');key('ArrowRight');expect(edits).not.toHaveBeenCalled();b.locked=false;key('a',{ctrlKey:true});b.disableConnections=true;key('Delete');expect(edits).not.toHaveBeenCalled();expect(b.selection).toHaveLength(7);b.requestEdit({type:'delete-selection',selection:b.selection});expect(edits).not.toHaveBeenCalled();});
});
