import { describe, expect, it } from "vitest";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import {
  adaptIconSvg,
  allocateIconKeys,
  discoverSourceIcons,
  generateIconsFromSource,
  normalizeIconColors,
  parseIconFilename,
  prefixIconIds,
  renderGeneratedManifest,
} from "../../tools/iconography/generate-box-iconography.js";

const FIXTURE_PACK = join(dirname(fileURLToPath(import.meta.url)), "../fixtures/iconography/pack");

describe("iconography generator", () => {
  it("parses Icon_*_{blue|white}*.svg filenames into slug bases", () => {
    expect(parseIconFilename("Icon_2-Chat-Question_blue.svg")).toEqual({
      base: "2-chat-question",
      tone: "blue",
    });
    expect(parseIconFilename("Icon_Arrow Right_white.svg")).toEqual({
      base: "arrow-right",
      tone: "white",
    });
    expect(parseIconFilename("Icon_4-Squares_blue-1.svg")).toEqual({
      base: "4-squares",
      tone: "blue",
    });
  });

  it("allocates unique keys with -2/-3 collision suffixes (blue before white)", () => {
    const allocated = allocateIconKeys([
      { filename: "Icon_Demo_blue.svg", tone: "blue" },
      { filename: "Icon_Demo_blue-1.svg", tone: "blue" },
      { filename: "Icon_Demo_white.svg", tone: "white" },
    ]);

    expect(allocated.map(entry => entry.key)).toEqual(["demo", "demo-2", "demo-3"]);
    expect(allocated.map(entry => entry.tone)).toEqual(["blue", "blue", "white"]);
  });

  it("normalizes paint to currentColor and prefixes ids", () => {
    const colored = normalizeIconColors(`<path fill="#0061D5" stroke="#fff"/><path fill="none"/>`);
    expect(colored).toContain('fill="currentColor"');
    expect(colored).toContain('stroke="currentColor"');
    expect(colored).toContain('fill="none"');

    const prefixed = prefixIconIds(
      `<g clip-path="url(#clip0)"><path/></g><clipPath id="clip0"/>`,
      "demo",
    );
    expect(prefixed).toContain('id="demo__clip0"');
    expect(prefixed).toContain("url(#demo__clip0)");
  });

  it("adapts a full SVG wrapper into viewBox + body", () => {
    const adapted = adaptIconSvg(
      `<svg viewBox="0 0 24 24"><circle id="dot" fill="#00F" cx="12" cy="12" r="10"/></svg>`,
      "spark",
    );
    expect(adapted.viewBox).toBe("0 0 24 24");
    expect(adapted.body).toContain('id="spark__dot"');
    expect(adapted.body).toContain('fill="currentColor"');
    expect(adapted.body).not.toContain("<svg");
  });

  it("discovers and generates icons from the fixture pack", () => {
    const discovered = discoverSourceIcons(FIXTURE_PACK);
    expect(discovered.length).toBe(4);

    const icons = generateIconsFromSource(FIXTURE_PACK);
    expect(icons.map(icon => icon.key)).toEqual(["arrow-right", "demo", "demo-2", "demo-3"]);

    // Filename sort puts Icon_Demo_blue-1.svg before Icon_Demo_blue.svg.
    const clipped = icons.find(icon => icon.filename === "Icon_Demo_blue.svg");
    expect(clipped?.key).toBe("demo-2");
    expect(clipped?.tone).toBe("blue");
    expect(clipped?.body).toContain("url(#demo-2__clip0_1_2)");
    expect(clipped?.body).toContain('id="demo-2__clip0_1_2"');
    expect(clipped?.body).toContain('fill="currentColor"');
    expect(clipped?.body).not.toContain("#0061D5");

    const white = icons.find(icon => icon.filename === "Icon_Demo_white.svg");
    expect(white?.key).toBe("demo-3");
    expect(white?.tone).toBe("white");
  });

  it("renders a TypeScript manifest that reloads with expected counts", () => {
    const icons = generateIconsFromSource(FIXTURE_PACK);
    const manifest = renderGeneratedManifest(icons);
    expect(manifest).toContain("auto-generated by tools/iconography/generate-box-iconography.ts");
    expect(manifest).toContain("export const boxGeneratedIcons");
    expect(manifest).toContain("total: 4");
    expect(manifest).toContain("blue: 3");
    expect(manifest).toContain("white: 1");

    const tempDir = mkdtempSync(join(tmpdir(), "boe-icons-"));
    const outFile = join(tempDir, "box-iconography.generated.ts");
    try {
      writeFileSync(outFile, manifest, "utf8");
      expect(readFileSync(outFile, "utf8")).toContain('"arrow-right"');
    } finally {
      rmSync(tempDir, { recursive: true, force: true });
    }
  });

  it("matches vendored key allocation for the committed metadata set", async () => {
    const { boxGeneratedIconMetadata } = await import(
      "../../src/foundations/icons/box-iconography.generated.js"
    );
    const files = Object.values(boxGeneratedIconMetadata).map(meta => ({
      filename: meta.filename,
      tone: meta.tone,
    }));
    const allocated = allocateIconKeys(files);
    const expectedByFilename = Object.fromEntries(
      Object.entries(boxGeneratedIconMetadata).map(([key, meta]) => [meta.filename, key]),
    );
    for (const entry of allocated) {
      expect(entry.key).toBe(expectedByFilename[entry.filename]);
    }
    expect(allocated).toHaveLength(Object.keys(boxGeneratedIconMetadata).length);
  });
});
